language: c

sudo: required

install:
 - sudo apt-get install qt5-qmake libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev-tools
 - sudo chmod 777 ./ -R

script:
 - mkdir boostdir
 - cd boostdir
 - git clone --depth=50 --branch=master https://github.com/boostorg/boost.git
 - mkdir ../src/boost
 - cp ./lib/thread ../src/boost -r
 - qmake
 - make
